### ISSUE TITLE
Ruby with OpenSSL 1.1.0f mingw / msys2 test-all failures

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/openssl#112]
For several months I've been using mingw/msys2 to build various Ruby versions on Windows.

I decided to make an msys2 package from OpenSSL 1.1.0e, then noticed that there were several backports, so I used the stable branch instead.  The package passes all tests.  When building Ruby with it, I have the following test-all failures:

```
 2) OpenSSL::TestASN1#test_decode              [test/openssl/test_asn1.rb:191]:
 3) OpenSSL::TestASN1#test_encode_utctime_2k38 [test/openssl/test_asn1.rb:272]:
 4) OpenSSL::TestOCSP#test_basic_response_der  [test/openssl/test_ocsp.rb:164]:
 5) OpenSSL::TestOCSP#test_request_der         [test/openssl/test_ocsp.rb:102]:
```

I believe these failures have occurred with previous Ruby / OpenSSL versions, including 1.0.2*.

Full result detail at gist [Summary make-all](https://gist.github.com/MSP-Greg/d07c6e42caa545bcff0407cd50197e75) (all tests, not just OpenSSL).  File is taken from log, comment on the bottom summarizes info.

I'm not a c type, so I can't determine where the problems are originating...

**Comment by rhenium** [comment]
It took me a while to figure out what is happening, because I didn't reproduce at first on my mingw64 build. The root cause is that Ruby and OpenSSL use different declaration of time_t. mingw uses 32-bit integer by default, but Ruby forces it to be 64-bit width by specifying __MINGW_USE_VC2005_COMPAT.

/mingw32/i686-w64-mingw32/include/_mingw.h:

~~~c
#if defined (_WIN32) && !defined (_WIN64) && !defined (__MINGW_USE_VC2005_COMPAT)
#ifndef _USE_32BIT_TIME_T
#define _USE_32BIT_TIME_T
#endif
#endif
~~~

/mingw32/i686-w64-mingw32/include/crtdefs.h:

~~~c
#ifndef _TIME_T_DEFINED
#define _TIME_T_DEFINED
#ifdef _USE_32BIT_TIME_T
typedef __time32_t time_t;
#else
typedef __time64_t time_t;
#endif
#endif /* _TIME_T_DEFINED */
~~~

Building OpenSSL with `./Configure -D__MINGW_USE_VC2005_COMPAT` fixes those test failures, but I don't know why Ruby uses that in the first place.

@nobu, do you have any ideas?

**Comment by MSP-Greg** [comment]
@rhenium Thanks for looking into it.

I apologize for not being clear whether the errors were for a i686 or a x86_64 build.  I've recently come across info re that flag `__MINGW_USE_VC2005_COMPAT`, but I don't recall where.  Regardless, I'll build and reply.  Might be a bit later, as it's 3:30 A here...

**Comment by MSP-Greg** [comment]
@rhenium

I have previously been using RubyInstaller to build.  It was essentially set up to either be 32 or 64, but not easily switched back and forth.  This morning I finally converted to building with makepkg-mingw.  I also rebuilt OpenSSL using `__MINGW_USE_VC2005_COMPAT`.

Results:
x86_64 passed all OpenSSL errors
i686 had the same failures mentioned in my first post.

**Comment by nobu** [comment]
I don't remember it well...
According to https://bugs.ruby-lang.org/issues/9119, something about TZ env.

**Comment by MSP-Greg** [comment]
@rhenium, @nobu 

Thank you for your help.  I had some consistency issues with testing the i686 build; had to add -j1 to a few of the make commands.   Once I got that straightened out, **OpenSSL 1.10e is passing all Ruby tests in test-all for both x86_64 & i686.**

Again, building with a custom mingw package created from code at [MSP-Greg/ruby-makepkg-mingw](https://github.com/MSP-Greg/ruby-makepkg-mingw).  Building Ruby using modified code based on [Alexpux/MINGW-packages/mingw-w64-ruby](https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-ruby).

Re test-all, i686 has 13 failures, 10 errors, 147 skips.  x86_64 has 9 failures, 12 errors, 149 skips.

Several of the issues seem related to 'access denied', temp files access, and the fact that my build environment is on D:, temp files are on C:, etc, etc.
