### ISSUE TITLE
Reading PEM/DER from an IO object fails with "no OPENSSL_Applink" error on mswin Ruby

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/openssl#128]
Please see [Ruby 13718 net/* tests using OpenSSL::PKey::RSA and OpenSSL::X509::Certificate](https://bugs.ruby-lang.org/issues/13718) for full info.

When running tests on a mswin trunk build with OpenSSL 1.1.0f, I have a silent stop with the following error:
```
OPENSSL_Uplink(000007FEEE4EE360,08): no OPENSSL_Applink
```

As mentioned in the issue, the current tests pass a File instance to `OpenSSL::PKey::RSA.new` and `OpenSSL::X509::Certificate.new`, instead of a string.

I assume an error should be generated, or they should accept a File/IO object, but they shouldn't silent stop with the above error.

**Comment by rhenium** [comment]
Thanks for the report, I could reproduce the problem with my x64-mswin64_140 Ruby by opening 20 files at a same time:

~~~
File.write("pkey.pem", OpenSSL::PKey::RSA.new(512).to_pem)
20.times.map { File.open("pkey.pem") }.each { |f| OpenSSL::PKey::RSA.new(f) }
~~~

The cause is that we don't provide OPENSSL_Applink(), but apparently OpenSSL only looks up the symbol in the application[1] (ruby.exe, in this case) where we can't place one.

I haven't come up with a good solution yet.

[1] https://github.com/openssl/openssl/blob/60eba30f60de55e3c782469fa555eede82606099/ms/uplink.c#L63

**Comment by MSP-Greg** [comment]
Thanks for looking into it.  I'm not that much of an OpenSSL user, so I don't know if IO would be a typical application.  I assume your build works fine with strings?

Also, if IO is common, maybe someone could (me?) could revise the docs to show that either strings or IO can be used?

I came across the issue running test-all, but verified it using:

```
ruby runner.rb -j3 -Ilib --show-skip net/ftp
```

on the test folder...

**Comment by rhenium** [comment]
Only the FILE BIO method and the file descriptor BIO method use the UPLINK interface, so yes, reading from String should work well on all platforms.

I have made it not use the FILE BIO at all by f842b0d5c5e37527c11954a4b7a98c8d9cc57865. Thanks.
