### ISSUE TITLE
OpenSSL::ASN1.decode yields OpenSSL::ASN1::Integer instances with a "value" attribute type of OpenSSL::BN

### ISSUE THREAD

**Issue by CBonnell** [ruby/openssl#176]
In OpenSSL gem 2.0.6 (using Ruby 2.4.2) and as far back as Ruby 2.2.1 (if not earlier), creating <code>OpenSSL::ASN1::Integer</code> instances using <code>OpenSSL::ASN1.decode</code> produces instances whose <code>value</code> attribute is of type <code>OpenSSL::BN</code>, not <code>Number</code> (which should probably be documented as <code>Integer</code>) as documented on the docs page for <code>OpenSSL::ASN1::Primitive</code> (<http://ruby-doc.org/stdlib-2.4.2/libdoc/openssl/rdoc/OpenSSL/ASN1/Primitive.html>).

Either <code>OpenSSL::ASN1.decode</code> should be modified to return <code>OpenSSL::ASN1::Integer</code> instances whose <code>value</code> attribute is of type <code>Integer</code>, not <code>OpenSSL::BN</code>. If this is not palatable from a backwards compatibility standpoint, this discrepancy should at least be documented.

Code to reproduce:
```ruby
require 'openssl'
puts OpenSSL::ASN1.decode("\x02\x01\x05").value.inspect
puts OpenSSL::ASN1::Integer.new(5).value.inspect
```

Expected output:
> 5
> 5

Actual output:
>#<OpenSSL::BN:0x007fe7818061f8>
> 5

**Comment by rhenium** [comment]
This behavior goes all the way back to Ruby 1.8.1 in 2003, when OpenSSL::ASN1 was initially introduced. It's not possible to change that because of compatibility. I'll fix the docs.

Regarding `OpenSSL::ASN1::Integer.new(5).value` returning Integer: it is because OpenSSL::ASN1::Primitive#initialize does not perform type checking. OpenSSL::ASN1::ASN1Data#value simply returns the value.
