### ISSUE TITLE
'initialize': invalid curve name (OpenSSL::PKey::ECError)

### ISSUE THREAD

**Issue by PavanTatikonda** [ruby/openssl#422]
Hello,

I'm running into the following error while trying to create new EC object from RSA private key file (Note:- I'm running this on alpine linux 3.13.1)

Ruby code: ```OpenSSL::PKey::EC.new IO.read key_file```
Error: ```'initialize': invalid curve name (OpenSSL::PKey::ECError)```

Below are my environment details:
```
~ # ruby --version
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux-musl]

~ # gem list | grep openssl
openssl (2.2.0, default: 2.1.2)
```

I've tried using openssl v2.1.2 but still seeing the same error. Any help is appreciated here!

Regards,
Pavan

**Comment by rhenium** [comment]
> EC object from RSA private key file

That's why: OpenSSL::PKey::EC handles ECC, not RSA. `OpenSSL::PKey::EC.new(string)` first attempts to parse `string` as DER or PEM encoded EC private/public key, and if that fails, it tries to generate a new key pair with the algorithm named `string`.

FYI - [`OpenSSL::PKey.read(string)`](https://ruby.github.io/openssl/OpenSSL/PKey.html#method-c-read) is the preferred way to parse encoded keys of an unknown key type.
