### ISSUE TITLE
OpenSSL udate 3.2.1 for CVE-2023-6129

### ISSUE THREAD

**Issue by fmonvoisin** [ruby/openssl#719]
Hello,

A new version 3.2.1 of openssl due to CVE-2023-6129 has been released.

My CVE scan tools report that the 3.2.0 openssl gem is vulnerable, does it need to be updated with the new version of openssl ?

Link for CVE : [Link CVE](https://www.cve.org/CVERecord?id=CVE-2023-6129)

Thank you for your help

**Comment by MSP-Greg** [comment]
In general, Ruby treats external packages as 'system' files, so it does not contain code to install OpenSSL on a user's system.

There are options for selecting a specific openssl install if more than one exists on a user's system.  These are based on file location, not version.

**Comment by kamyarz-aws** [comment]
@hsbt how about this CVE-2023-5363? Is it the same case ?

**Comment by junaruga** [comment]
@kamyarz-aws

If you just search by the keyword "CVE-2023-5363", you can find the following NIST website. I rely on this website. Then you find the references to the advisories on the page. You see the links about the summary, and patch file. In this case, I see some links from "openssl.org" such as [this](https://www.openssl.org/news/secadv/20231024.txt). So, the security issue CVE-2023-5363 is for OpenSSL (openssl/openssl) not for Ruby OpenSSL (ruby/openssl).

https://nvd.nist.gov/vuln/detail/CVE-2023-5363

One more way I am using is to search a CVD ID such as "CVE-2023-5363" on the [Red Hat Bugzilla](https://bugzilla.redhat.com/), you can find [the issue ticket](https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2023-5363). You see the "Fixed In Version: 	OpenSSL 3.0.12, OpenSSL 3.1.4" or comments that may be the clues for you to understand which component caused the issue.

I hope this tips are helpful for you to investigate how to check a security issue's component by yourself.
