### ISSUE TITLE
Document support for SNI

### ISSUE THREAD

**Issue by c-knowles** [ruby/openssl#81]
The [current documentation](http://ruby-doc.org/stdlib-2.3.1/libdoc/openssl/rdoc/OpenSSL/SSL/SSLSocket.html) does not list any support for SNI although it can be done as `OpenSSL::SSL::SSLSocket#hostname=` and is referenced in https://github.com/ruby/openssl/issues/8. Is it officially supported?

In openssl, it can be done via `-servername HOST` so the naming does not match and hence it would be good to get it documented. Note, I found this via [stackoverflow](http://stackoverflow.com/questions/30244745/opensslsslsslcontext-sni-servername-cb-not-working). 

Given that the [code](https://github.com/ruby/openssl/blob/master/lib/openssl/ssl.rb#L246) wraps the attribute in `if ExtConfig::HAVE_TLSEXT_HOST_NAME`, I'm not sure about the best way to get this appearing in rdoc.

**Comment by rhenium** [comment]
Yes, it is part of the public API, since Ruby 1.9.2 (note it requires OpenSSL >= 0.9.8f).

RDoc comment was fixed some time ago, and OpenSSL::SSL::SSLSocket#hostname= now shows up in the latest HTML generated from the master branch:

http://ruby.github.io/openssl/OpenSSL/SSL/SSLSocket.html#method-i-hostname-3D

**Comment by c-knowles** [comment]
Great, thanks! Those docs are definitely nicer than the ones currently on ruby-doc.org.
