### ISSUE TITLE
[RFE] Enable to configure default ciphers

### ISSUE THREAD

**Issue by voxik** [ruby/openssl#90]
In Fedora, we have policy [1], which should assure a consistent security level for crypto on all applications in a Fedora system. However, since [2], the default cipher set was overridden, which changed now again (so luckily, the system defaults should be used for recent OpenSSL) if I understand b9aea270fbe1 correctly.

The main difficulty is that this is not transparent and moreover it is hard to adjust for me as a maintainer. Therefore, would it be possible, to introduce some configuration option, to modify the behavior explicitly? E.g.

```
gem install openssl -- --cipher-list="PROFILE=SYSTEM"
```

would explicitly allow to set the cipher compliant with the system policy.

Please note that if this was implemented, I intend to ask for similar Ruby configuration option.

[1] https://fedoraproject.org/wiki/Packaging:CryptoPolicies
[2] https://bugs.ruby-lang.org/issues/9424

**Comment by rhenium** [comment]
My understanding is that the white list added in [Bug #9424] was a temporary and one-time exception until OpenSSL starts providing sane defaults. OpenSSL 1.1.0 is the first version that satisfies this, so I changed in the commit so that the white list won't be used for OpenSSL >= 1.1.0 (in other words, no calls of SSL_CTX_set_cipher_list() by default). I don't think we will re-add such a list in the future.

**Comment by voxik** [comment]
But there used to be different explicit list for past 10 years (see https://github.com/ruby/ruby/commit/2c038353963843b8dfa7850b0b34023437b2174d). But if you think that you won't change the default list again in the foreseeable future, I am fine if you close the ticket.

**Comment by rhenium** [comment]
Yes, I think we won't want to do it again.
